//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int Id_book { get; set; }
        public int Id_Busket { get; set; }
        public int Quantity { get; set; }
        public decimal SumOrder { get; set; }
    
        public virtual Basket Basket { get; set; }
        public virtual Book Book { get; set; }
    }
}
